import { Sora } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import Header from '@/components/Header'
import TopLeftImg from '@/components/TopLeftImg'

const sora = Sora({ 
  subsets: ['latin'],
  variable:'--font-sora',
  weight:['100','200','300','400','500','600','700','800']

 })


export const metadata = {
  title: 'Portfolio',
  description: 'Generated by thiruppathi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} relative`}>
          <TopLeftImg/>
          <Nav/>
          <Header/>
        {children}
        </div>
      
      </body>
    </html>
  )
}
