import { Sora } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import Header from '@/components/Header'
import TopLeftImg from '@/components/TopLeftImg'
import { AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/router'
'use client'
const sora = Sora({ 
  subsets: ['latin'],
  variable:'--font-sora',
  weight:['100','200','300','400','500','600','700','800']

 })


export const metadata = {
  title: 'Portfolio',
  description: 'Generated by thiruppathi',
}

export default function RootLayout({ children }) {
  const router = useRouter()
  return (
    <html lang="en">
      <body >
        <AnimatePresence mode='wait'>
        <div className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} relative`}>
          <TopLeftImg/>
          <Nav/>
          <Header/>
        {children}
        </div>
        </AnimatePresence>
       
      
      </body>
    </html>
  )
}
